"""Turn the OCR sweep into a canonical per-location conditions table."""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from dr2server.game_data import Location, STAGE_CONDITIONS_LABELS

# UI stage-area name (as OCR'd) -> Location enum member.
NAME_TO_LOCATION = {
    'CATAMARCA PROVINCE': 'ARGENTINA', 'MONARO': 'AUSTRALIA', 'JAMSA': 'FINLAND',
    'BAUMHOLDER': 'GERMANY', 'ARGOLIS': 'GREECE', 'MONTE CARLO': 'MONTE_CARLO',
    'HAWKES BAY': 'NEW_ZEALAND', 'LECZNA COUNTY': 'POLAND', 'RIBADELLES': 'SPAIN',
    'VARMLAND': 'SWEDEN', 'NEW ENGLAND': 'NEW_ENGLAND', 'POWYS': 'WALES',
    'PERTH AND KINROSS': 'SCOTLAND',
    'METTET': 'METTET', 'TROIS-RIVIERES': 'TROIS_RIVIERES',
    'LYDDEN HILL': 'LYDDEN_HILL', 'SILVERSTONE': 'SILVERSTONE',
    'LOHEAC BRETAGNE': 'LOHEAC', 'ESTERING': 'ESTERING',
    'BIKERNIEKI': 'BIKERNIEKI', 'MONTALEGRE': 'MONTALEGRE',
    'KILLARNEY INTERNATIONAL RACEWAY': 'KILLARNEY',
    'CIRCUIT DE BARCELONA-CATALUNYA': 'BARCELONA', 'HOLJES': 'HOLJES',
    'VAS MARINA CIRCUIT': 'YAS_MARINA',
    # "HELL" is too short for reliable OCR in this font; both readings are it.
    '| i ,': 'HELL', 'al i ,': 'HELL',
}


def key(label):
    return label.replace(' Surface', '').strip().lower()


LBL2ID = {}
for cid, lbl in STAGE_CONDITIONS_LABELS.items():
    LBL2ID.setdefault(key(lbl), []).append(cid)

raw = json.loads(Path('data/verified/conditions_by_location.json').read_text())
byloc, unknown = {}, {}
for name, labels in raw.items():
    if not labels:
        continue
    loc = NAME_TO_LOCATION.get(name)
    if loc is None:
        print(f'!! unmapped probe name: {name!r}')
        continue
    ids, unk = [], []
    for l in labels:
        got = LBL2ID.get(key(l))
        if got:
            ids.append((min(got), l.replace(' Surface', '')))
        else:
            unk.append(l.replace(' Surface', ''))
    byloc[loc] = ids
    if unk:
        unknown[loc] = unk

order = [l.name for l in Location]
print('# generated by scripts/_build_conditions_table.py')
for loc in order:
    if loc not in byloc:
        print(f'    # {loc}: no data')
        continue
    ids = byloc[loc]
    print(f'    Location.{loc}: (' + ', '.join(str(i) for i, _ in ids) + ',),')
    for i, lbl in ids:
        print(f'        # {i:>2} {lbl}')
    for u in unknown.get(loc, []):
        print(f'        # -- {u}  (offered in-game; id not yet known)')
print()
print('locations with no usable id:', [l for l in order if l in byloc and not byloc[l]])
print('locations absent entirely:', [l for l in order if l not in byloc])
